Feature/merches,users,achiev models
Praktikum-Am-CRM/backend pull request #1
Opened 2024-02-25 15:52 UTC by greenpandorik

1. Сделана модель merches
2. Сделана модель achievements
3. Сделана модель users/manager
4. Добавлен pre-commit для единого оформления кода
5. Сделан workflows для единого оформления кода

2024-02-25 16:07 UTC, teamofroman requested changes
1. Давай не завязываться на статический набор статусов. Лучше пусть это будет таблица, в которой они будут лежать. Это облегчит добавление новых статусов в будущем.
2. В модели Manager надо добавить обязательным поле email. По нему идет авторизация.
3. Модель RequestAmbassador по сути является промежуточной таблицей для организации связи многие-ко-многим между амбассадором и мерчами. Поэтому там фактически должно быть два поля (оба типа ForeignKey на соответствующие модели) - ambassador и request
4. Мы везде в качестве базовых используем одинарные кавычки. Добавь соответствующую настройку к black

2024-02-25 20:21 UTC, greenpandorik commented
Исправил комментарии выше.

2024-02-26 17:48 UTC, greenpandorik commented
Поправил модели исходя из новых вводных

2024-02-27 18:57 UTC, teamofroman requested changes
Отлично.
Несколько замечаний.

2024-02-27 18:57 UTC, teamofroman commented on merches/models.py
> +class Status(models.Model):
Можно удалить. (см комментарий ниже по коду)

2024-02-27 18:57 UTC, teamofroman commented on merches/models.py
> +        null=True,
`null=False`
У нас не может быть запроса для амбассадора без запроса мерча

2024-02-27 18:57 UTC, teamofroman commented on merches/models.py
> +        Status,
Пропустил связку. Здесь надо ссылаться на таблицу `DeleviryStatus`

2024-02-27 18:57 UTC, teamofroman commented on merches/models.py
> +        null=True,
Зачем `null=True`? У нас поле может принимать только 2 значения - `True` или `False`

2024-02-27 18:57 UTC, teamofroman commented on merches/admin.py
> +    Status,
Можно убрать (см. комментарий ниже)

2024-02-27 18:57 UTC, teamofroman commented on merches/admin.py
> +admin.site.register(Status)
Аналогично

2024-02-28 05:40 UTC, greenpandorik commented on merches/admin.py
> +    Status,
Убрать всё из админки или только то что ты выделил ?

2024-02-28 05:40 UTC, greenpandorik commented on merches/admin.py
> +admin.site.register(Status)
Убрать всё из админки или только то что ты выделил ?

2024-02-28 05:40 UTC, greenpandorik commented on merches/models.py
> +        null=True,
```
available = models.BooleanField(
        default=False
    )
```

Тогда делаю так ?

2024-02-28 05:41 UTC, greenpandorik commented on merches/models.py
> +class Status(models.Model):
Удалить Амбассадора же ? Ты про это? Просто без него пре коммит не проходит и остальное. Давай оставлю а потом как смерджим код с моделью амбассадора, уберу его

2024-02-28 06:13 UTC, teamofroman commented on merches/models.py
> +class Status(models.Model):
Нет, удалить только класс Status, заменив ссылки на него на класс `DeliveryStatus` (он у тебя ниже по коду)

2024-02-28 06:16 UTC, greenpandorik commented on merches/models.py
> +class Status(models.Model):
Понял, поправил

2024-02-28 06:18 UTC, teamofroman commented on merches/models.py
> +        null=True,
По умолчанию считаем что `available=True`

2024-02-28 06:19 UTC, teamofroman commented on merches/admin.py
> +    Status,
Вместо `Status` будет `DeliveryStatus`

2024-02-28 06:19 UTC, teamofroman commented on merches/admin.py
> +admin.site.register(Status)
См выше...

2024-02-28 06:38 UTC, teamofroman approved these changes
Отлично

2024-02-28 06:38 UTC, merged