Feature/tests for allmodels
Praktikum-Am-CRM/backend pull request #12
Opened 2024-03-02 20:46 UTC by greenpandorik

1. Сделал тесты для всех моделей

2024-03-03 11:39 UTC, teamofroman requested changes
Отлично, но:
1. Давай не будем в блоке тестирования вносить изменения в модели (мы же пишем тесты и проверяем, как должно быть. Вносить изменения в модели будем в ветках `fix/...`
2. Соответственно включать в коммит эти изменения не надо.
3. Видимо под тестами моделей мы с тобой понимаем разные вещи. В моем понимании тест модели - это больше проверка соответствия ее атрибутов атрибутам, заданным в модели данных.  Сейчас править не будем, надо сосредоточиться на тестах для ендпоинтов. Если останется время - допишем.
4. Ну и на последок маленькое замечание в файле `users/models.py`

2024-03-03 11:39 UTC, teamofroman commented on users/models.py
> +        return " ".join(names) if any(names) else self.username or self.email
Если кто-то из `self.last_name`, `self.first_name`, `self.middle_name` имеет значение `None`, код вывалится с ошибкой.

2024-03-03 16:43 UTC, greenpandorik commented on users/models.py
> +        return " ".join(names) if any(names) else self.username or self.email
Исправил

2024-03-03 16:44 UTC, greenpandorik commented on users/models.py
> +        return " ".join(names) if any(names) else self.username or self.email
`def get_full_name(self) -> str:
        """ФИО."""
        names = [
            name for name in (
                self.last_name, self.first_name, self.middle_name
                ) if name is not None
        ]
        return " ".join(names)`

2024-03-04 16:03 UTC, greenpandorik commented
1. Поправил тесты
2. Поправил модель сразу тут , и старое изменение в модели откатить уже не могу. Так как потрачу много времени, тесты не будут на старой модели проходить. Но я учёл что больше в ветке с тестами модели менять не буду.

2024-03-04 16:35 UTC, teamofroman approved these changes
Отлично

2024-03-04 16:35 UTC, merged