Feature/reports. Model, serializer and adminsite registration
Praktikum-Am-CRM/backend pull request #2
Opened 2024-02-25 17:02 UTC by Rederickmind

2024-02-25 17:05 UTC, Rederickmind commented
Сделана модель Reports, а также Placement, RunStatus и TypeReport
Добавил сериализатор для оценки с 1 до 10
Зарегистрировал модели в админке

2024-02-26 19:19 UTC, teamofroman requested changes
Отлично.
Немного надо причесать (часть из-за моего косяка, каюсь...)

2024-02-26 19:19 UTC, teamofroman commented on backend/reports/migrations/0001_initial.py
> +# Generated by Django 4.2.7 on 2024-02-25 15:16
Давай сейчас это файл не будем включать в комит. Потом сделаем общую миграцию, когда будут готовы все модели.

2024-02-26 19:19 UTC, teamofroman commented on backend/settings.py
>      'djoser',
Тоже пока не надо пушить этот файл, если все изменения касаются только добавления приложений.

2024-02-26 20:36 UTC, Rederickmind commented on backend/reports/admin.py
> +# class PostAdmin(admin.ModelAdmin):
Этот комментарий был на случай если нам нужно будет в админке листом что-то отобразить.
Как пример как я это делал в учебном проекте, но ок, пока удалил.

2024-02-26 20:40 UTC, Rederickmind commented on backend/settings.py
>      'djoser',
Убрал

2024-02-26 20:40 UTC, Rederickmind commented on backend/reports/migrations/0001_initial.py
> +# Generated by Django 4.2.7 on 2024-02-25 15:16
Удалил

2024-02-27 19:00 UTC, teamofroman commented on backend/reports/models.py
> +        unique=True,
А почему уникальная? Может у него канал в телеграмм.
Давай уберем уникальность

2024-02-27 19:38 UTC, teamofroman commented
1. Обрати внимание, папка `media` является корневой для всех медиа файлов и указывать в пути ее не надо.
2. И вынеси приложение `reports` из папки `backend` на уровень выше. `backend` это папка с настройками проекта :)

2024-02-27 20:48 UTC, Rederickmind commented
> 1. Обрати внимание, папка `media` является корневой для всех медиа файлов и указывать в пути ее не надо.
> 2. И вынеси приложение `reports` из папки `backend` на уровень выше. `backend` это папка с настройками проекта :)

1. Поправил
2. Вынес, но мне почему-то кажется что это сломает приложение и надо будет заново его инициализировать.

Сделал отдельным коммитом, если что откатим или сделаем заново вставив код из этих файлов.

2024-02-27 20:49 UTC, Rederickmind commented on backend/reports/models.py
> +        unique=True,
Мне кажется ссылка идет именно на пост, а она с уникальным идентификатором обычно. Но в целом не критично

2024-02-28 06:22 UTC, teamofroman approved these changes
Отлично

2024-02-28 06:23 UTC, merged