Feature/ambassador
Praktikum-Am-CRM/backend pull request #4
Opened 2024-02-27 15:59 UTC by DimaBack85

Переделал модели

2024-02-27 19:34 UTC, teamofroman requested changes
Отлично получилось.
Есть некоторые замечания (в т.ч. и в связи с изменениями в модели данных)

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +        "Telegram_bot",
Модель называется `TelegramBot`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +        "Status",
Наверное `AmbassadorStatus`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +    promocode = models.CharField(
Давай ограничим по длине до 255 символов

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +    reminder_counter = models.IntegerField(
Счетчик напоминаний не может быть меньше 0.
Давай использовать модель `PositiveIntegerField`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +    adress_index = models.CharField(
Индекс обязательная часть почтового адреса.
Поэтому он не может быть пустым.

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +    size_choe = models.IntegerField(
Размер обуви не может быть меньше 0.
Давай использовать модель PositiveIntegerField

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +from django.core.validators import MinLengthValidator
Общее замечания на файл.
1. Давай ограничим длину текстовых полей. Значения можно посмотреть здесь https://drive.google.com/file/d/1PXNEhU8ILFYL2lp_5i5vjfBcSc8yQhkx/view
2. У каждой модели надо переопределить поле `id` с числового на `uuid`
```python
id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        unique=True
    )
```

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +    type_of_activity = models.CharField(
Поле называется `activity_name`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +    report_status = models.CharField(
Поле называется `status_name`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +    available = models.BooleanField()
Надо добавить значение по умолчанию - `True`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +class Goal(models.Model):
Надо добавить поле `available = models.BooleanField(default=True)`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +class Activity(models.Model):
Надо добавить поле `available = models.BooleanField(default=True)`

2024-02-27 19:34 UTC, teamofroman commented on ambassador/models.py
> +class Achive(models.Model):
Надо добавить поле `available = models.BooleanField(default=True)`

2024-02-27 19:34 UTC, teamofroman commented on messages/models.py
> +    message_telegram_id = models.ForeignKey(
Это поле перенесено в модель `BotMessages`, что бы проще было делать сериализатор и сортировку при необходимости.
Тип поля - строка. Это номер сообщения в телеграмме, который он присваивает каждому сообщению. В одном чате не может быть двух сообщений с одним номером. Телеграм сам за этим следит.

2024-02-27 19:34 UTC, teamofroman commented on messages/models.py
> +    reaction = models.IntegerField()
Это поле перенесено в модель `BotMessages`, что бы проще было делать сериализатор и сортировку при необходимости.

2024-02-27 19:34 UTC, teamofroman commented on messages/models.py
> +from django.db import models
Общее замечания на файл.
1. Давай ограничим длину текстовых полей. Значения можно посмотреть здесь https://drive.google.com/file/d/1PXNEhU8ILFYL2lp_5i5vjfBcSc8yQhkx/view
2. У каждой модели надо переопределить поле `id` с числового на `uuid`
```python
id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        unique=True
    )
```

2024-02-27 19:34 UTC, teamofroman commented on messages/models.py
> +    sign_AI = models.BooleanField(
В именах переменных и членах класса давай использовать маленькие буквы.

2024-02-27 19:34 UTC, teamofroman commented on messages/models.py
> +    message_type = models.TextField()
Имя поля - `type_name` и давай использовать тип поля `CharField`, что бы можно было ограничить его длину

2024-02-27 19:34 UTC, teamofroman commented on messages/models.py
> +    media_link = models.URLField()
На схеме данных да, представление этого поля - URI, а в модели оно будет обеспечивать хранение файла, который будет прицеплен к сообщению. Поэтому здесь надо использовать `FileField`.

2024-02-27 19:34 UTC, teamofroman commented on messages/models.py
> +    message_status = models.TextField(
Название поля - `status_name` и давай использовать тип поля `CharField`, что бы можно было ограничить его длину

2024-02-28 02:05 UTC, DimaBack85 commented on ambassador/models.py
> +        "Status",
В модели именно Статус

2024-02-28 02:05 UTC, DimaBack85 commented on ambassador/models.py
> +        "Telegram_bot",
Поменял

2024-02-28 06:28 UTC, teamofroman commented on ambassador/models.py
> +        "Status",
Модель приведена к единообразию (на сколько это возможно)
Сейчас таблица со статусом амбассадора называется `ambassador_status`, ну и класс, соответственно, `AmbassadorStatus`
https://app.diagrams.net/#G1Hdz7GBhJdb_ZiCLL6Qwn932seaS-bVUq#%7B%22pageId%22%3A%22m8FwTI9sg_kWhUP1caG7%22%7D

2024-02-29 04:49 UTC, teamofroman approved these changes
Ок

2024-02-29 04:51 UTC, merged